name: tests-tickets

on:
  pull_request:
    paths:
      - 'backend/node/tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd backend/node/tickets && npm install && npm run test:ci
