name: tests-auth

on:
  pull_request:
    paths:
      - 'backend/node/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd backend/node/auth && npm install && npm run test:ci
