name: tests-orders

on:
  pull_request:
    paths:
      - 'backend/node/orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd backend/node/orders && npm install && npm run test:ci
